---
# Handlers for node_exporter role

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
  become: true

- name: Restart otel-collector
  ansible.builtin.systemd:
    name: otelcol-contrib
    state: restarted
  become: true
