---
# Variables for hosts in network_agents group

network_agent_proxy_host: "agent.proxcet.io:443"
network_agent_sync_interval: "30s"
network_agent_enable_ipv4_forwarding: true
network_agent_enable_ipv6_forwarding: true
