---
# Install Proxy Agent on hosts in proxy_agents group
#
# Usage:
#   ansible-playbook -i inventories/production playbooks/proxy-agent.yaml
#   ansible-playbook -i inventories/production playbooks/proxy-agent.yaml --limit goproxy1

- name: Install Proxy Agent
  hosts: proxy_agents
  become: true

  roles:
    - role: proxy_agent
